// levels.js
// 地圖符號：
// # 牆/岩壁, . 路, S 起點, E 出口
// K 鑰匙/符文石, D 門, B 路障, T 陷阱, I 加分道具, M 怪獸, P 傳送門
// 角色方向：0上 1右 2下 3左
//
// ✅重要修正：每一關的每一列字串長度都一致（避免關卡無法顯示）
// ✅世界1：依序 6x6 → 7x7 → 8x8 → 9x9 → 10x10（循序加大）

window.LEVELS = [
  // =========================================================
  // 世界 1：序列（只用：向前走 / 左轉 / 右轉）
  // 地圖大小：第1關 6x6，依序加大到第5關 10x10
  // =========================================================
  {
    worldId: "W1",
    worldName: "世界1｜魔法學院（序列）",
    theme: {
      accent: "#7c5cff",
      accent2: "#31d0ff",
      wallBg: "rgba(35,28,85,.80)",
      wallBd: "rgba(180,140,255,.22)",
      itemBg: "rgba(124,92,255,.16)",
      itemBd: "rgba(124,92,255,.28)",
      blockBg: "rgba(255,146,64,.16)",
      blockBd: "rgba(255,146,64,.28)",
    },
    unlockRule: { type: "always" },
    levels: [
      {
        levelId: "L1",
        name: "第1關：學院大門",
        targetSteps: 5,
map: [
  "#####",
  "#.#..",
  "SKD.E",
  "#.#C.",
  "#####",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"%E*?lM,B/aa@m=darYC2\" x=\"64\" y=\"66\"><next><block type=\"mw_move_forward\" id=\"o?CZsCLdVR_,{ZnKh6Pi\"><next><block type=\"mw_move_forward\" id=\"ZatCr79.F{DQ3lMBh+ld\"><next><block type=\"mw_turn_right\" id=\"cVM*)_{V)WF@fKV5Cz[7\"><next><block type=\"mw_move_forward\" id=\"zMKgb-4Oia[ys@+t7L2K\"><next><block type=\"mw_turn_left\" id=\"=!|7{oEoreaDDL^73ls!\"><next><block type=\"mw_move_forward\" id=\"%p|bG*--~N*7wi3byE^w\"><next><block type=\"mw_turn_left\" id=\"|[|qEN#.-,;,=8O/:*N7\"><next><block type=\"mw_move_forward\" id=\"R{q|Y~6N0;qMz@lJ@r@%\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",},
      {
        levelId: "L2",
        name: "第2關：分岔路口",
        targetSteps: 8,
map: [
  "#####",
  "#.D.E",
  "SK###",
  "#...C",
  "#####",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"S?-Aqro{1uQYce#r2s%4\" x=\"-50\" y=\"-310\"><next><block type=\"mw_turn_right\" id=\"cJ[c%bHtavk{{t7xRx4$\"><next><block type=\"mw_move_forward\" id=\"hprd`Ae02C7*b%1YKc2I\"><next><block type=\"mw_turn_left\" id=\"u{Y[;QeD55_TgE%S2PPj\"><next><block type=\"mw_move_forward\" id=\"z-O@(0*_]UWA5d}~,ToA\"><next><block type=\"mw_move_forward\" id=\"7Ow|j@x~cJdWTL{yci0T\"><next><block type=\"mw_move_forward\" id=\"BPxbL)DA-|_^:uKA%7hm\"><next><block type=\"mw_turn_left\" id=\"aGgRoon5:.sRU@B#]293\"><next><block type=\"mw_turn_left\" id=\"No1;}2SOO*rPS?gR^9tI\"><next><block type=\"mw_move_forward\" id=\"?dwu]v90KBoqntj:~]0d\"><next><block type=\"mw_move_forward\" id=\"J]7hnpkscObGmKBVB%,|\"><next><block type=\"mw_move_forward\" id=\"daIpPTp-Zxm^d6T#ndtn\"><next><block type=\"mw_turn_right\" id=\"=dKJY!Z]*~5ZOilJ4fu?\"><next><block type=\"mw_move_forward\" id=\"xOk/oPAX:,4YSudT%zbA\"><next><block type=\"mw_move_forward\" id=\"`u/^!R#g)Y^Ndf^CH9VL\"><next><block type=\"mw_turn_right\" id=\"^LPiABvf{q26vL`4_BBp\"><next><block type=\"mw_move_forward\" id=\"z_puUK{*/{b^8ihd/{f:\"><next><block type=\"mw_move_forward\" id=\"sS-tMb_EPvlrVH**}lci\"><next><block type=\"mw_move_forward\" id=\"i|b9T`iEGy~:EeI;Sjuh\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",      },
      {
        levelId: "L3",
        name: "第3關：此路不通",
        targetSteps: 8,
        map: [
  "#####",
  "S.B.E",
  "#.#.#",
  "#...C",
  "#####",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"{Y,l)Ia{L;_TA!;]WoLb\" x=\"-290\" y=\"-410\"><next><block type=\"mw_turn_right\" id=\"~~X/VVG1$$%8S%4s2A^Q\"><next><block type=\"mw_move_forward\" id=\"a,d`obSuJGG$F[^i`?a2\"><next><block type=\"mw_move_forward\" id=\"NTRO!LNlu|B6}CC4~(}k\"><next><block type=\"mw_turn_left\" id=\"CM.UC3J@UbC@~4?,tsyL\"><next><block type=\"mw_move_forward\" id=\"BPq7V^%|!^.o*c@#oSk-\"><next><block type=\"mw_move_forward\" id=\"n-8d|Udc+yB7:d;iqm?=\"><next><block type=\"mw_move_forward\" id=\"}BWfMRQ6sFP8mJ7$6#{:\"><next><block type=\"mw_turn_left\" id=\"##!),=*@-!,k?DSZga+q\"><next><block type=\"mw_turn_left\" id=\"cO*$-F{3G8rYwVUUw1.}\"><next><block type=\"mw_move_forward\" id=\"7QSfMr{pHGpz,y{Dlpod\"><next><block type=\"mw_turn_right\" id=\"pf5A=8/E1,dxB[6nRS;T\"><next><block type=\"mw_move_forward\" id=\")=vM_len[PNdN0e;C[v6\"><next><block type=\"mw_move_forward\" id=\"XAt?S2KyD:b:v|a*B8#X\"><next><block type=\"mw_turn_right\" id=\";4NbNq5sv!Yx7wB(iEDF\"><next><block type=\"mw_move_forward\" id=\"qhm9Pk@yi)$)UW+AWxHM\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",      },
      {
        levelId: "L4",
        name: "第4關：小心陷阱",
        targetSteps: 8,
        map: [
  "#####",
  "S.T.E",
  "#.##.",
  "#....",
  "##C##",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"[V-ZB_qbR1it[7dcJI|=\" x=\"10\" y=\"-130\"><next><block type=\"mw_turn_right\" id=\"$^MO@$~i~u#eTK0j8i2#\"><next><block type=\"mw_move_forward\" id=\"Bfph]+AmA6IZVN`k9i}f\"><next><block type=\"mw_move_forward\" id=\";G0=jPv!/UYN1}{pNV^G\"><next><block type=\"mw_turn_left\" id=\"a@9XlL~nA:TsC{{J!,Nw\"><next><block type=\"mw_move_forward\" id=\"]UsPYF$!J{Yh5YZYUWT~\"><next><block type=\"mw_turn_right\" id=\"28%{=@W[]8[HYekF:j;+\"><next><block type=\"mw_move_forward\" id=\"Ze*7MNG}Q3(ob-SDo]G(\"><next><block type=\"mw_turn_right\" id=\"oF:pYWGS[qm:X8wG5{!f\"><next><block type=\"mw_turn_right\" id=\"%8;L8q(:sRvK`[WovNt`\"><next><block type=\"mw_move_forward\" id=\"4zi%2(;4K?5pf9qVslD%\"><next><block type=\"mw_turn_right\" id=\"VXNMByOCzJx]2jHj0^,H\"><next><block type=\"mw_move_forward\" id=\"|Ha.jz^;bUosww#,0vq@\"><next><block type=\"mw_move_forward\" id=\"YC-%b]W%7Ou9$t?7;t(U\"><next><block type=\"mw_turn_left\" id=\"[+MXN(QY07DewY3q{PdV\"><next><block type=\"mw_move_forward\" id=\"X`oK#P}{MeJBtlWC6w0L\"><next><block type=\"mw_move_forward\" id=\"A3I_wSd]$=3j_D=4Glft\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",      },
      {
        levelId: "L5",
        name: "第5關：入學測驗",
        targetSteps: 10,
        map: [
  "#I###",
  "S.B.C",
  "#....",
  "#T.#.",
  "#..DE",
],
        startDir: 1,
        bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"j8l`L{4:Tt{0%v/q1xk;\" x=\"30\" y=\"30\"><next><block type=\"mw_turn_left\" id=\":nDS`R,}[Zm/=YlteN3K\"><next><block type=\"mw_move_forward\" id=\"dOX%!f?z8OkVsE`l7MO_\"><next><block type=\"mw_turn_left\" id=\".+brAq{vsc`w9cD[w/y(\"><next><block type=\"mw_turn_left\" id=\"Ay1@O6M1{g8rL];a#]FT\"><next><block type=\"mw_move_forward\" id=\"tej}2SFKUvQwGD-%LQ:k\"><next><block type=\"mw_move_forward\" id=\"K#Cg=|cVBT?YY`#XYywH\"><next><block type=\"mw_turn_left\" id=\"aI#+GQpP,zEY~K0aq+F}\"><next><block type=\"mw_move_forward\" id=\"OFn-ua_Ff{MrYFG.|qS^\"><next><block type=\"mw_move_forward\" id=\"bM~WBs1R8{BI-g@tB/{U\"><next><block type=\"mw_move_forward\" id=\"N(wOT%9;;W40fp?Rb7sK\"><next><block type=\"mw_turn_left\" id=\"jfW/|-q?UN#CC;gMu;$N\"><next><block type=\"mw_move_forward\" id=\"Tr#Zn~KQOEc`Aj/DvqE$\"><next><block type=\"mw_turn_left\" id=\"1bqY4H`3$oa`X;u%eA*R\"><next><block type=\"mw_turn_left\" id=\"[L%AWB~[c!.13~b:_d_g\"><next><block type=\"mw_move_forward\" id=\"T|-Zyu:iC6$+}%t_%.[j\"><next><block type=\"mw_move_forward\" id=\"?x`i?_v`g9w?GgAG57sX\"><next><block type=\"mw_move_forward\" id=\"yo/2JY2//8u=)MJ|HYb?\"><next><block type=\"mw_move_forward\" id=\"KCM,~sToLEpr|MsAFqNz\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",
      },
    ],
  },

  // =========================================================
  // 世界 2：迴圈（解鎖：重複）
  // ✅完成世界1五關才解鎖
  // =========================================================
  {
    worldId: "W2",
    worldName: "世界2｜符文森林（迴圈）",
    theme: {
      accent: "#3ddc84",
      accent2: "#31d0ff",
      wallBg: "rgba(14,50,40,.82)",
      wallBd: "rgba(61,220,132,.22)",
      portalBg: "rgba(78,227,165,.16)",
      portalBd: "rgba(78,227,165,.28)",
      monsterBg: "rgba(255,92,124,.16)",
      monsterBd: "rgba(255,92,124,.28)",
      itemBg: "rgba(61,220,132,.12)",
      itemBd: "rgba(61,220,132,.22)",
    },
    unlockRule: { type: "passCountInWorld", worldId: "W1", need: 5 },
    levels: [
      {
        levelId: "L1",
        name: "第1關：符文護身",
        targetSteps: 16,
        map: [
  "#######",
  "#S....#",
  "#####.#",
  "#.....#",
  "#.###M#",
  "#....E#",
  "#######",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"controls_repeat_ext\" id=\"m72$.(5$Js*]0p6UxYc$\" x=\"-30\" y=\"-130\"><value name=\"TIMES\"><block type=\"math_number\" id=\"yN/6-D3iJIkkQFwi|8qm\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"4C%xlJxhy^O.UHEPs^uL\"/></statement><next><block type=\"mw_turn_right\" id=\"qw={Ou$vD:EXcre#g45w\"><next><block type=\"mw_move_forward\" id=\"6_KXm87:6AK%+YLS(@i:\"><next><block type=\"mw_move_forward\" id=\"9q_9w1b4c(Hy1~Ejf/gO\"><next><block type=\"mw_turn_right\" id=\"b,K~_g.9}4pJBDU%cKg_\"><next><block type=\"controls_repeat_ext\" id=\"-7F2]x`c(Cm)#3q!La%|\"><value name=\"TIMES\"><block type=\"math_number\" id=\"z]3Vp}Jo($d#5AZWNY7Z\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"CTJs#w06[9O8ON2;.18v\"/></statement><next><block type=\"mw_turn_left\" id=\"hm{3prFn#cslWLFK3J[#\"><next><block type=\"controls_repeat_ext\" id=\"=Xt$5zu~FlJ*;V`Q2XsS\"><value name=\"TIMES\"><block type=\"math_number\" id=\"EXdz,{Ds,yCm.LEQ.EtL\"><field name=\"NUM\">2</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"ouRZND*m{Wj#yO?YpUBD\"/></statement><next><block type=\"mw_turn_left\" id=\"5w_wtfGzY@0kdn}@yz(j\"><next><block type=\"controls_repeat_ext\" id=\",%5p|+fCbA@,{{C]ctv2\"><value name=\"TIMES\"><block type=\"math_number\" id=\"z(UT8j-K9:ZXlg,s0r7W\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"42}oP|riAw,pm5EzxE8p\"/></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",      },
      {
        levelId: "L2",
        name: "第2關：傳送門捷徑",
        targetSteps: 18,
        map: [
  "#######",
  "S.MK..P",
  "#.#...#",
  "#KM.#M#",
  "#.#.MME",
  "#.MC#M#",
  "#P#####",
],
        startDir: 1,
bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"mw_move_forward\" id=\"E`9=YX`QDE703cNaOnM)\" x=\"65\" y=\"-51\"><next><block type=\"mw_turn_right\" id=\"5EzLb:xFJ{6$}oIzn2f1\"><next><block type=\"controls_repeat_ext\" id=\"jzygPwp[(W4vLnj6^Zk:\"><value name=\"TIMES\"><block type=\"math_number\" id=\"DH_2.zxf7U:sJCEDul2E\"><field name=\"NUM\">5</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"PR35N;Wz1;$Wv*5`!z*:\"/></statement><next><block type=\"mw_turn_right\" id=\"b@)Y[iA1~`uG;)~$,H}w\"><next><block type=\"controls_repeat_ext\" id=\"610-(X|T+Be,4I]KkaFL\"><value name=\"TIMES\"><block type=\"math_number\" id=\",}OR?$9=I}O(SrK/VIdk\"><field name=\"NUM\">3</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"-bM)V;}~%/TC|#OjLO!o\"/></statement><next><block type=\"mw_turn_left\" id=\"iS!`Y5^V4+w.=F:`zC5Y\"><next><block type=\"controls_repeat_ext\" id=\"KtDZsht?T-zxPAd2b!PC\"><value name=\"TIMES\"><block type=\"math_number\" id=\"`2^fK_b;~6Ci5-FJBTfs\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"c3icT2wh`#vPMq_]=MT:\"/></statement><next><block type=\"mw_turn_left\" id=\"=pUvfJJZ!t.jUEK0#t*J\"><next><block type=\"mw_turn_left\" id=\"^EAgkWxYT}lP#fK0[Pd.\"><next><block type=\"mw_move_forward\" id=\"K*,}B{alY7-_ij(c#Uxe\"><next><block type=\"mw_turn_right\" id=\"d-4~tZ{@{Oc)HLr7W}xb\"><next><block type=\"controls_repeat_ext\" id=\"AMn=?vLX;mZ!9,W$q[,p\"><value name=\"TIMES\"><block type=\"math_number\" id=\"Oj1}}(x;+(ti2P_:+JcS\"><field name=\"NUM\">3</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"~3n(f/tUU1(,X!C{V650\"/></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",      },
      {
        levelId: "L3",
        name: "第3關：藤蔓陷阱",
        targetSteps: 22,
        map: [
  "#######",
  "#S...K#",
  "#.#P..#",
  "#T#T#T#",
  "#.#P#.#",
  "#C.M.E#",
  "#######",
],
        startDir: 1,
        bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"controls_repeat_ext\" id=\"LOKCx(6#8NEBa-@sJy]_\" x=\"59\" y=\"-120\"><value name=\"TIMES\"><block type=\"math_number\" id=\"77?8K[K1NkDRFJ,wqH$L\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"9Zl~f[~5plAgqOJio/1J\"/></statement><next><block type=\"mw_turn_right\" id=\"-$zv59.0?z(=R,I/@afM\"><next><block type=\"mw_move_forward\" id=\"#svs0we]SRmTE=k,X{Ib\"><next><block type=\"mw_turn_right\" id=\"poFN*;B[6#b2WYrI.D:@\"><next><block type=\"controls_repeat_ext\" id=\"nxINz[,]3Sky_!UuIw3p\"><value name=\"TIMES\"><block type=\"math_number\" id=\"kK!B/utuc0eGOt^T*/YJ\"><field name=\"NUM\">2</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"Ly^}t#7.+G.Q[qQ(1=9x\"/></statement><next><block type=\"mw_turn_left\" id=\"w6!.PYCcU=+QL8rw{nuw\"><next><block type=\"mw_move_forward\" id=\"+rgt0!/~_641YPY]R^Q;\"><next><block type=\"mw_turn_right\" id=\"RS$5=C2GPk!1Ckb3b[m,\"><next><block type=\"controls_repeat_ext\" id=\"{zDDYM.?lZhFu2P0I~+I\"><value name=\"TIMES\"><block type=\"math_number\" id=\"9A/]rM*[qP8wae;:3K!O\"><field name=\"NUM\">2</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"J`^(RPm]G5@rj1nzbXGJ\"/></statement><next><block type=\"mw_turn_right\" id=\"}E-]/,.]Rm0/HFqTBxp(\"><next><block type=\"mw_turn_right\" id=\"}Nqt-r:JJXzD.|=3Z8sU\"><next><block type=\"controls_repeat_ext\" id=\"c7HQs(7(@*qHo3r6UP#R\"><value name=\"TIMES\"><block type=\"math_number\" id=\"H94+JH-kZV,Y~H6Eubc3\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"P/w1jmT;#dal!b3ftjSG\"/></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",
      },
      {
        levelId: "L4",
        name: "第4關：採集蘑菇",
        targetSteps: 24,
        map: [
  "######P",
  "#S..K.I",
  "#T#####",
  "#C.T.##",
  "##..K.I",
  "#M.##.M",
  "#P###ME",
],
        startDir: 1,
        bestXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"controls_repeat_ext\" id=\"RaK`-8{JFNPpGaTLdEb)\" x=\"-99\" y=\"-185\"><value name=\"TIMES\"><block type=\"math_number\" id=\"N0l@O,-51s@jK/FFg4mo\"><field name=\"NUM\">5</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"-S1occVN}qu5pLng6t/x\"/></statement><next><block type=\"mw_turn_left\" id=\"ySa{KMj!eaxW.jS_0^/J\"><next><block type=\"mw_move_forward\" id=\"4ieM__3u[WRmPRXV7]q;\"><next><block type=\"mw_move_forward\" id=\"iMXg_,`qTlnysC7wly,/\"><next><block type=\"mw_turn_right\" id=\"-.==bit!5L0EkyUX,jSC\"><next><block type=\"mw_move_forward\" id=\"-6.$SL/#2)!Bs/CVlH0I\"><next><block type=\"mw_turn_left\" id=\"HU@.F4Qul.S}5l8myiam\"><next><block type=\"controls_repeat_ext\" id=\";2s5BQGE(Bduyj-FOy3]\"><value name=\"TIMES\"><block type=\"math_number\" id=\"_|qy?*X}NZavrw~$SU:U\"><field name=\"NUM\">2</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"EPF%LUvO8%[6oVpQ4Q?P\"/></statement><next><block type=\"mw_turn_left\" id=\"jt}/zKS%|bZ[I_^pf75a\"><next><block type=\"mw_move_forward\" id=\"e~@z$X]M,oEGi+nF+gnb\"><next><block type=\"mw_turn_left\" id=\"2HjX4A2OOd-Onmx4ld~I\"><next><block type=\"mw_turn_left\" id=\"|*bCmAslhP]by$K`J1L-\"><next><block type=\"mw_move_forward\" id=\"1`b?H@TY,%=QklF6bBBt\"><next><block type=\"mw_turn_right\" id=\"ma{H9k*SVHtF!dPI@E,I\"><next><block type=\"mw_move_forward\" id=\"gCvbUY:Ptcr(+RY]~6#W\"><next><block type=\"mw_turn_left\" id=\"LrM$4R?om)Vil$x3f9`s\"><next><block type=\"controls_repeat_ext\" id=\"I5w?Jh02MQ|.j.Z]gFFJ\"><value name=\"TIMES\"><block type=\"math_number\" id=\"y`]b_*cT33+~yn9]}sNV\"><field name=\"NUM\">4</field></block></value><statement name=\"DO\"><block type=\"mw_move_forward\" id=\"k3X-PksIvM9@Iay2Ms%D\"/></statement><next><block type=\"mw_turn_right\" id=\"o;X0FGCD~h{WORDyN3Oy\"><next><block type=\"mw_move_forward\" id=\"gL)76O%iyA!gvQZt$n,|\"><next><block type=\"mw_move_forward\" id=\"T4Hs%h4G2;SR?kuKxJEM\"/></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></xml>",
      },
      {
        levelId: "L5",
        name: "第5關：森林守門者",
        targetSteps: 26,
        map: [
          "###########",
          "#S..P.....#",
          "#.###.###.#",
          "#...#...#.#",
          "###.#.#.#.#",
          "#K..#.#.#.#",
          "#.###.#.#.#",
          "#..C#.#...#",
          "#.###.###M#",
          "#P....I..E#",
          "###########",
        ],
        startDir: 1,
        bestXml: "",
      },
    ],
  },

  // =========================================================
  // 世界 3：條件式（解鎖：如果 + 前方有路？）
  // =========================================================
  {
    worldId: "W3",
    worldName: "世界3｜時光圖書館（條件式）",
    theme: {
      accent: "#ffd26e",
      accent2: "#31d0ff",
      wallBg: "rgba(70,55,20,.82)",
      wallBd: "rgba(255,210,110,.22)",
      itemBg: "rgba(255,210,110,.12)",
      itemBd: "rgba(255,210,110,.22)",
      monsterBg: "rgba(255,92,124,.14)",
      monsterBd: "rgba(255,92,124,.25)",
      portalBg: "rgba(49,208,255,.14)",
      portalBd: "rgba(49,208,255,.22)",
      blockBg: "rgba(255,146,64,.14)",
      blockBd: "rgba(255,146,64,.25)",
    },
    unlockRule: { type: "passCountInWorld", worldId: "W2", need: 5 },
    levels: [
      {
        levelId: "L1",
        name: "第1關（教學）：條件轉彎練習",
        targetSteps: 20,
        map: [
          "#############",
          "#S...K......#",
          "#.#########.#",
          "#...........#",
          "#.#########.#",
          "#.....I.....#",
          "#.#########.#",
          "#.....D.....#",
          "#.#########.#",
          "#.........C.#",
          "#.#########.#",
          "#..........E#",
          "#############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L2",
        name: "第2關：迷路書架（轉彎很多）",
        targetSteps: 22,
        map: [
          "#############",
          "#S.....#....#",
          "#.###.#.#.#.#",
          "#...#.#.#.#.#",
          "###.#.#.#.#.#",
          "#...#...#K#.#",
          "#.#####.#.#.#",
          "#.....#.#.#.#",
          "#.###.#.#.#.#",
          "#.#...#...#.#",
          "#.#.#####.#C#",
          "#....D....E##",
          "#############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L3",
        name: "第3關：陷阱書頁（T）",
        targetSteps: 28,
        map: [
          "#############",
          "#S....#.....#",
          "#.###.#.###.#",
          "#...#...#...#",
          "###.###.#.###",
          "#..T....#...#",
          "#.#####.###.#",
          "#...#.....#.#",
          "#.###.###.#.#",
          "#...#...#.#.#",
          "#.###.#.#.#.#",
          "#K.CP#...D.E#",
          "#############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L4",
        name: "第4關：傳送書庫（P）",
        targetSteps: 22,
        map: [
          "#############",
          "#S....#C....#",
          "#.###.#.###.#",
          "#...#.#...#.#",
          "###.#.###.#.#",
          "#...#...#.#.#",
          "#.#####.#.#.#",
          "#P....#.#...#",
          "#.###.#.###.#",
          "#...#.#.....#",
          "#.###.#####.#",
          "#K..#....P.E#",
          "#############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L5",
        name: "第5關：館長試煉（綜合）",
        targetSteps: 24,
        map: [
          "#############",
          "#S....#C....#",
          "#.###.#.###.#",
          "#...#.#...#.#",
          "###.#.###.#.#",
          "#...#..I#.#.#",
          "#.#####.#.#.#",
          "#..T..#.#...#",
          "#.###.#.###.#",
          "#...#.#.....#",
          "#.###.#####.#",
          "#K..#..P.M.E#",
          "#############",
        ],
        startDir: 1,
        bestXml: "",
      },
    ],
  },

  // =========================================================
  // 世界 4：函式（解鎖：咒語A / 咒語B）
  // =========================================================
  {
    worldId: "W4",
    worldName: "世界4｜機械城堡（函式）",
    theme: {
      accent: "#ff5c7c",
      accent2: "#31d0ff",
      wallBg: "rgba(60,15,25,.82)",
      wallBd: "rgba(255,92,124,.22)",
      itemBg: "rgba(255,92,124,.12)",
      itemBd: "rgba(255,92,124,.22)",
      portalBg: "rgba(49,208,255,.14)",
      portalBd: "rgba(49,208,255,.22)",
      monsterBg: "rgba(255,210,110,.14)",
      monsterBd: "rgba(255,210,110,.22)",
      blockBg: "rgba(255,146,64,.14)",
      blockBd: "rgba(255,146,64,.25)",
    },
    unlockRule: { type: "passCountInWorld", worldId: "W3", need: 5 },
    levels: [
      {
        levelId: "L1",
        name: "第1關（教學）：咒語入門（重複走法）",
        targetSteps: 25,
        map: [
          "###############",
          "#S....#....K..#",
          "#.###.#.#####.#",
          "#...#.#.......#",
          "###.#.###.###.#",
          "#...#.....#...#",
          "#.#####.###.#.#",
          "#.....#.....#.#",
          "#.###.#####.#.#",
          "#...#.....#.#.#",
          "#.#####.#.#.#.#",
          "#.....#.#.#...#",
          "#.###.#.#C###.#",
          "#....D...#..E.#",
          "###############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L2",
        name: "第2關：齒輪核心（I / P）",
        targetSteps: 25,
        map: [
          "###############",
          "#S..I.#.......#",
          "#.###.#.#####.#",
          "#...#.#...P...#",
          "###.#.###.###.#",
          "#...#.....#...#",
          "#.#####.###.#.#",
          "#..K..#.....#.#",
          "#.###.#####.#.#",
          "#...#.....#.#.#",
          "#.#####.#.#.#.#",
          "#.....#.#.#...#",
          "#.###.#.#C###.#",
          "#....D...#P.E.#",
          "###############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L3",
        name: "第3關：蒸汽陷阱（T / I）",
        targetSteps: 25,
        map: [
          "###############",
          "#S....#.......#",
          "#.###.#.#####.#",
          "#...#.#...T...#",
          "###.#.###.###.#",
          "#...#.....#...#",
          "#.#####.###.#.#",
          "#..K..#..I..#.#",
          "#.###.#####.#.#",
          "#...#.....#.#.#",
          "#.#####.#.#.#.#",
          "#.....#.#.#...#",
          "#.###.#.#C###.#",
          "#....D.M.#..E.#",
          "###############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L4",
        name: "第4關：管線傳送（P）",
        targetSteps: 25,
        map: [
          "###############",
          "#S..P.#.......#",
          "#.###.#.#####.#",
          "#...#.#.......#",
          "###.#.###.###.#",
          "#...#.....#...#",
          "#.#####.###.#.#",
          "#..K..#..T..#.#",
          "#.###.#####.#.#",
          "#...#.....#.#.#",
          "#.#####.#.#.#.#",
          "#.....#.#.#...#",
          "#.###.#.#C###.#",
          "#....D...#P.E.#",
          "###############",
        ],
        startDir: 1,
        bestXml: "",
      },
      {
        levelId: "L5",
        name: "第5關：城堡終章（大綜合）",
        targetSteps: 25,
        map: [
          "###############",
          "#S....#.......#",
          "#.###.#.#####.#",
          "#...#.#...P...#",
          "###.#.###.###.#",
          "#...#..I..#...#",
          "#.#####.###.#.#",
          "#..K..#..T..#.#",
          "#.###.#####.#.#",
          "#...#.....#.#.#",
          "#.#####.#.#.#.#",
          "#.....#.#.#...#",
          "#.###.#.#C###.#",
          "#....D.M.#P.E.#",
          "###############",
        ],
        startDir: 1,
        bestXml: "",
      },
    ],
  },
];
